Definition of a pragma for boolean type.
argotorg/solcore pull request #48
Opened 2024-11-29 17:03 UTC by rodrigogribeiro

Initial implementation for a pragma for setting up the boolean type. Current syntax definition:

```
data bool = true | false;

pragma bool-type-decl bool, true, false;
```

2024-12-02 10:25 UTC, mbenke commented
What's the intended meaning? To translate declared true/false to Yul true/false/ Anything else? 
Perhaps also if/while when we have them? Maybe we should think how they should work.

2024-12-02 11:10 UTC, rodrigogribeiro commented
> What's the intended meaning? To translate declared true/false to Yul true/false/ Anything else? Perhaps also if/while when we have them? Maybe we should think how they should work.

That's my main question: What should I do with this information? Should I add if / while statements to the surface syntax?

2024-12-10 10:28 UTC, mbenke requested changes
It's very hard to tell what changed when actual changes are mixed with big reformatting. Could you please split this PR in two (reformatting, actual pragma stuff)?

2024-12-10 10:28 UTC, mbenke commented on src/Solcore/Frontend/Syntax/Pragma.hs
> +  deriving (Eq, Ord, Show, Data, Typeable)
I don't know what `PragmaStatus` is, please add comment in code

2024-12-10 10:33 UTC, mbenke commented
Something is missign in prettyprinter:

```
$ cabal run -- sol-core -v -f test/examples/pragmas/booltypesyntax.solc
> AST after name resolution
sol-core: src/Solcore/Frontend/Pretty/SolcorePretty.hs:(56,3)-(58,46): Non-exhaustive patterns in function ppr
```

2024-12-10 10:50 UTC, mbenke commented on src/Solcore/Frontend/Pretty/SolcorePretty.hs
> +    hsep [text "pragma", ppr ty, ppr st, semi]
```suggestion
instance Pretty Pragma where
  ppr (InferencePragma _ Enabled) = empty
  ppr (InferencePragma ty st) =
    hsep [text "pragma", ppr ty, ppr st, semi]
  ppr (BoolTypePragma (ty N.:| cons)) =
    text "pragma bool-type-decl" <+> commaSep (map ppr (ty:cons))
    
```

2025-06-02 15:56 UTC, d-xo commented
> > What's the intended meaning? To translate declared true/false to Yul true/false/ Anything else? Perhaps also if/while when we have them? Maybe we should think how they should work.
> 
> That's my main question: What should I do with this information? Should I add if / while statements to the surface syntax?

IIRC we need this for at least two things:

1. short circuiting for boolean ops (this will need compiler magic since we're in a strict eval context)
2. surface level `if`/`for`/`while`

2025-06-02 15:58 UTC, d-xo commented
> It's very hard to tell what changed when actual changes are mixed with big reformatting. Could you please split this PR in two (reformatting, actual pragma stuff)?

Agree, this is impossible to review as is. @rodrigogribeiro how much work would it be to tidy this up? We could also just close it if it's significant effort, since this pr is not needed for the stuff we're focusing on right now.

2025-06-05 11:53 UTC, rodrigogribeiro commented
> > It's very hard to tell what changed when actual changes are mixed with big reformatting. Could you please split this PR in two (reformatting, actual pragma stuff)?
> 
> Agree, this is impossible to review as is. @rodrigogribeiro how much work would it be to tidy this up? We could also just close it if it's significant effort, since this pr is not needed for the stuff we're focusing on right now.

Most of these changes have been made in other commits. The implementation of Boolean type was left aside due other more pressing fixes on type inference. I'll close this PR, since it does not make sense currently.

2025-06-05 11:53 UTC, closed without merging